
#se.yml

version: "2"
services:
    server:
        build:
            context: .
        restart: always
        ports:
            - 5000:5000
        networks:
            - db-net
        depends_on:
            - db
    db:
        image: mysql:8.0.20
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        volumes:
            - ./db/init:/docker-entrypoint-initdb.d
            - ./db/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - db-net
        ports:
            - 8086:3306
    redis-server:
        image: "redis"
networks:
    db-net:
